import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthWrapper from "./components/auth/AuthWrapper";
import { CookieService } from "@/classes/database/CookieService";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieObject = CookieService.getCookies();

  console.log("Cookie object");
  console.log(cookieObject);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthWrapper
          value={{
            authenticated: cookieObject?.authenticated ?? false,
            userCookies: cookieObject,
          }}
        >
          {children}
        </AuthWrapper>
      </body>
    </html>
  );
}
